package testutil

import (
	"os"
	"testing"
)

// TestGenRandSize checks that fiels generated by GenRand are the correct size.
func TestGenRandSize(t *testing.T) {
	var fileSize int64 = 1024 * 1024
	filePath := "./tmpfile"
	err := GenRandFile(filePath, fileSize)
	if err != nil {
		t.Fatal("Error generating:", err)
	}

	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatal("Error statting:", err)
	}

	if info.Size() != fileSize {
		t.Fatal("File size is incorrect")
	}

	err = os.Remove(filePath)
	if err != nil {
		t.Fatal("Error removing file:", err)
	}
}
